spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        enabled: true
        model: "nomic-embed-text"
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        max-document-batch-size: 10000 # Maximum number of documents per batch
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/llm_assistant
    username: llm_assistant
    password: pw123
